
viewer = siteviewer("Buildings","J_St_osm_map.osm","Basemap","topographic","Terrain","gmted2010");

tx = txsite("Name","Transmitter", ...
    "Latitude",47.479144592781360, ...
    "Longitude",19.056184959090420, ...
    "AntennaHeight",1.5, ...
    "TransmitterPower",0.1, ...
    "TransmitterFrequency",5.9e9);
show(tx)

rtpm = propagationModel("raytracing", ...
    "Method","sbr", ...
    "MaxAbsolutePathLoss", 120,...
    "MaxNumReflections",8, ...
    "BuildingsMaterial","glass", ...
    "TerrainMaterial","concrete");

coverage(tx,rtpm, ...
    "SignalStrengths", -120:-20, ...
    "MaxRange",250, ...
    "Resolution",3, ...
    "Transparency",0.6);